apiVersion: v1
kind: Namespace
metadata:
  name: torchspec-k26
---
apiVersion: v1
kind: Secret
metadata:
  name: novitalabs
  namespace: torchspec-k26
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30=
